# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment WorkFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy house-planning
      uses: appleboy/ssh-action@master
      with:
       host: 204.236.138.9
       username: ubuntu
       key: ${{ secrets.PLANNING_BE}}
       port: 22
       script: |
         cd be/be-housing-plan-approval-system
         git pull origin master
         pm2 start app.js


    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x]

    # steps:
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # - run: npm run build --if-present
    # - name: Deploy to Server
    #   uses: easingthemes/ssh-deploy@v2.1.5
    #   env:
    #       SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
    #       ARGS: "-rltgoDzvO --delete"
    #       SOURCE: "dist/"
    #       REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #       REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #       TARGET: ${{ secrets.REMOTE_TARGET }}
