# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment WorkFlow FE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
       host: 204.236.138.9 
       username: ubuntu
       port: 22
       key: ${{ secrets.PLANNING_FE }}
       source: "dist/*"
       target: "fe/"
    # - name: deploy house-planning fe
    #   uses: appleboy/ssh-action@master
    #   with:
    #    host: 204.236.138.9
    #    username: ubuntu
    #    key: ${{ secrets.PLANNING_FE}}
    #    port: 22
    #    script: |
    #       sudo systemctl restart nginx


    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x]

    # steps:
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # - run: npm run build --if-present
    # - name: Deploy to Server
    #   uses: easingthemes/ssh-deploy@v2.1.5
    #   env:
    #       SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
    #       ARGS: "-rltgoDzvO --delete"
    #       SOURCE: "dist/"
    #       REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #       REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #       TARGET: ${{ secrets.REMOTE_TARGET }}





  
      

